apiVersion: apps/v1
kind: Deployment
metadata:
  name: interactive-resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interactive-resume
  template:
    metadata:
      labels:
        app: interactive-resume
    spec:
      containers:
        - name: interactive-resume
          image: singshre2025/interactive-resume:latest
          ports:
            - containerPort: 5000
